### ISSUE TITLE
[!] Could not find that company name

### ISSUE THREAD

**Issue by thatsecguy** [initstring/linkedin2username#11]
Hi @initstring 

Testing this out and I keep getting the above error, irrespective of the company name used (even tried uber-com as a test). 

Script output is as follows,

[*] Using version 0.10, which is the latest on Gitlab.

[*] Successfully logged in.

[!] Could not find that company name. Please double-check LinkedIn and try again.

**Comment by initstring** [comment]
Hi @thatsecguy ,

Thank you very much for taking the time to open this ticket!

I just ran the tool several times and it is working perfectly for me. You must have hit an interesting error condition that I haven't accounted for. I would love to figure this out so I can output a better error message for others encountering it.

Can you try:
- Run it on another machine and/or from another network. Possibly something local on your machine or possibly a proxy/web filter/etc in your network
- Share with me the command exactly as you are running it (anonymize your email address)

If that doesn't work, it would be helpful if I could have the GET request that is causing this issue. You can use the --proxy feature to run it through Burp suite. If you wouldn't mind sharing the HTTP response to the GET /company/whatever request with me. You can anonymize it as needed and share it with me at my username at protonmail.com if you are comfortable doing that.

If you can't share that, I understand, and perhaps we can troubleshoot another way.

Thanks again!

**Comment by thatsecguy** [comment]
Hi @initstring 

Tried another machine and connecting via mobile connection, still the same result. The exact command is as follows,

./linkedin2username.py myemail@myemailprovider.com uber-com

I have mailed you the GET requests.

Thanks

**Comment by initstring** [comment]
Thanks for providing debugging details and helping me troubleshoot.

For anyone reading, the fix was to use a VPN with an exit point in Australia (probably other major countries would be ok too). LinkedIn appears to force a low-bandwidth template to some users, which is not compatible with li2u.

I am investigating what fix to implement - that ticket is on GitLab [here](https://gitlab.com/initstring/linkedin2username/issues/12).

Closing this ticket.

Thanks!
