### ISSUE TITLE
I can only get a few names.

### ISSUE THREAD

**Issue by Fanghero** [initstring/linkedin2username#13]

**Comment by initstring** [comment]
Hello,
Thanks for taking the time to open a ticket! I'll need a bit more info than this to help, though.
The tool seems to be working properly for me. Is it possible you are not within 3 degrees of connections of anyone at the target company?
Can you please provide the command you are running and the output you received? If you'd prefer, you can email it to me directly at my username here at protonmail.com.

**Comment by initstring** [comment]
Closing due to lack of information and no reply. Please re-open if you'd like to provide more info.
