### ISSUE TITLE
Cannot login with valid credentials

### ISSUE THREAD

**Issue by bigrob69** [initstring/linkedin2username#15]
the following error is received upon logging in with valid and working credentials

"Some unknown error logging in. If this persists, please open an issue on github."

**Comment by initstring** [comment]
Hi @bigrob69,
Thank you very much for opening a ticket!
I just tested the script and it is working properly with my account, which at least means LI hasn't changed their site so much to completely break the tool.
Occasionally, they make changes to failed login attempts that break my current error catching, though.
To troubleshoot, I would need more info. If you'd like, you can run the tool with the --proxy switch, send it through BurpSuite or ZAP, and see if you can determine what the error is. You can share an anonymized version of the replies with me if you feel comfortable doing that. You can email them to me at my username at protonmail.com.
I would also just make sure you can log in via the web from the same source IP you are running the tool as, just to make sure there is nothing funky going on there.
Hopefully we can get to the bottom of this.
Thanks!

**Comment by initstring** [comment]
No reply, closing. If you are still having issues, please let me know.
Thanks!
