### ISSUE TITLE
Tool doesn't work well with "compound" names

### ISSUE THREAD

**Issue by mugruith** [initstring/linkedin2username#16]
**Describe the bug**
Output is messed up when you use the tool on employees with compound names separated with an - `(eg. Jean-Pierre)`
The tool is outputing 2 results for one target:
jean.name@company.com & pierre.name@company.com

**To Reproduce**
Use the tool on a French company for example, where compound names are really common.

**Verify Expected Results**
Expected result may vary depending on the companies, could be the following :
jeanpierre.name@company.com
jean-pierre.name@company.com
jpierre.name@company.com

**Comment by initstring** [comment]
Hi @phantasmthewhite 

Thank you very much for taking the time to open this issue! This is great feedback and I will implement your recommendation soon.

**Comment by initstring** [comment]
Hi @phantasmthewhite 

I'm so sorry to have left this idle for so long. Unfortunately, I am quite busy with a few other projects, a new job, and just life in general. This is way at the bottom of the list in terms of things I need to work on.

I'll leave the issue open - if many people are struggling with this, I will try to prioritize. Or if someone submits a fix I will review and merge, as long as it doesn't impact standard usage.

If you just want a quick fix for yourself, you can take a look at the function that writes to the file and just pile on a bunch. I didn't want to go that route as it will generate lots of extra usernames when generally not required, and a proper solution unfortunately means changes to the core way I process names.

Thanks!

**Comment by initstring** [comment]
Closing this one as "will not fix". Unfortunately, I don't have the time to implement this one. I would be open to a pull request if someone puts it together.

Sorry!!!
