### ISSUE TITLE
Encounter:  found_desc = ["RegEx issues, please open a ticket on GitHub!"]

### ISSUE THREAD

**Issue by joviledog** [initstring/linkedin2username#19]
Set the company name to -c thrivent

The HTTP response came back with a JSON response but the regular expression 

findall(desc_regex, response.text)

could not find the tagline description from this even though the other results could be found.
[thrivent.txt](https://github.com/initstring/linkedin2username/files/3976706/thrivent.txt)

**Comment by initstring** [comment]
Thank you for opening this! I'll queue it up to take a look when I have some free time, probably later this week.
I appreciate you taking the time to let me know, it's very helpful.

**Comment by initstring** [comment]
Turns out the description could just be legit not added, or added in some other areas.
I took the path of least resistance and simply changed the error for this one.
Thanks!
