### ISSUE TITLE
not graping more then 5 user on a 5000 company

### ISSUE THREAD

**Issue by VozDeOuro** [initstring/linkedin2username#20]
https://pastebin.com/iu4AY2wQ
i have at least 3° connection type on more then 500
command usage 
./linkedin2username.py -c sos -g -u email@email.com.br -n "companny.com.br"

**Comment by initstring** [comment]
Thanks for opening this issue!
I can reproduce the problem when searching for big companies in Brazil, so I think this must be related to something with the geo codes I am using, or possibly LinkedIn has done a change to the way they search per region.
I'll try to look deeper into this, but am a bit busy at the moment so it may take some time.
Please let me know if you figure it out in the meantime.

Thanks!

**Comment by VozDeOuro** [comment]
and about the Looping through region at:0|be:0|bg:0|hr:0|cz:0|dk:0|fi:0

this numbers should to be 0?
i run the tool 2 days ago in another small company and every thing was right i don't know why now it's not runnig 
i will wait for you look deeper

Thanks for the fast answer, i let you update with that if i get it

**Comment by initstring** [comment]
Closing as I don't have time to troubleshoot this myself and haven't received any other reports. Open to PRs if anyone else encounters this and finds a solution.
