### ISSUE TITLE
[!] Some unknown redirection occurred

### ISSUE THREAD

**Issue by fgpalacios** [initstring/linkedin2username#22]
**Describe the bug**
I execute the code python3 linkedin2username.py -c sos -g -u myemail@gmail.com 
-n "uber.com" -p mypassord

**To Reproduce**
Please provide the command as you ran it, omitting the target company name if necessary and of course your username and password.
I tried to proof the first example but allways get the same error message: 
[!] Some unknown redirection occurred. If this persists, please open an issue on github.

**Verify Expected Results**
Have you verified that you can access the company page via the web UI, and that the expected amount of contacts are visible using your login?
yes.

**Additional context**
Do you have any type of special setup? Web proxy, two-factor LI authentication, etc.
No.

**Comment by initstring** [comment]
Thanks for taking the time to open an issue!

I've just pushed some changes that will hopefully print a debug message with more details when you get that error. Can you try again? This should provide some hints as to what is going on. If the debug message doensn't have any sensitive info in it, would you mind sharing here?

Thanks!

**Comment by LioMasterRIE** [comment]
![image](https://user-images.githubusercontent.com/38889163/94909691-d8e50480-04a3-11eb-9803-74bca718a6cd.png)
having the same issue
running kali in Vmware (I tried NAT, bridge and isolated network)

**Comment by initstring** [comment]
Hi @LioMasterRIE 

Looks like it is redirecting you to some sort of account check thing. Can you try logging in via the web browser and making sure it's not asking you to do something?

If you've already tried that - is there something in the RESPONSE TEXT debug message there? I'm not sure if the screenshot cut it off.

Thanks for reporting the issue!

**Comment by LioMasterRIE** [comment]
nothing in debug message .....

but you were RIGHT !!! linkedin was asking for something after logging back  in !!
THANKS , my issue is resolved

**Comment by initstring** [comment]
Thanks!

Closing this issue as never heard back from the original reporter.
