### ISSUE TITLE
result files are empty

### ISSUE THREAD

**Issue by LioMasterRIE** [initstring/linkedin2username#24]
**Describe the bug**
I can see user in linkedin but the tools return nothing 
--> files are empty, no users

**To Reproduce**
/linkedin2username.py -u email@xxxx.fr -p password -c company

**Verify Expected Results**
all is ok in linkedin (there are anonymous and no-anonymous profiles)

**Additional context**
![image](https://user-images.githubusercontent.com/38889163/94912767-74787400-04a8-11eb-9740-c48650d7eb50.png)

**Comment by initstring** [comment]
Hmmm... I've never tried the tool on a company with so few users.

I did just try on a larger company and verified it is working for me, so at least LinkedIn hasn't changed something so big to completely break it.

If you want to share the company name with me, you can email it to me at initstring with the domain protonmail.com.

If you can't share that, I understand of course but may not be able to help.

**Comment by LioMasterRIE** [comment]
here is a company (taken at random) with 10 users : isomec-srl
and the result is the same : nothing in the files

with google company I had a lot of results (it seems it is working for big company )

**Comment by initstring** [comment]
I get 5 names from that company, and they show up properly in the output files. That is the same amount of people whose full names are visible in the web when I log in, as well.

So it seems to be working as expected, even with small companies (at least for me - LinkedIn can be really inconsistent).

Maybe you need to add more connections to the account you are logging in as?

You can see what is happening inside the tool by running ZAP or Burp and appending the `--proxy localhost:8080` flag.

You'll see a request that looks something like `GET /voyager/api/search/hits?facetCurrentCompany...`

In the HTTP response body on that request, search for "firstName" and you'll see the raw API results that this tool parses. If you see lots of valid combos of firstName/lastName in that reply but not in the output, then something is wrong.

**Comment by LioMasterRIE** [comment]
how you run your app to use proxy ?
-x 127.0.0.1:8080 ?
I tried -x localhost but have issue
![image](https://user-images.githubusercontent.com/38889163/94926942-da252a00-04c1-11eb-869f-6f90bc346dcd.png)
![image](https://user-images.githubusercontent.com/38889163/94926766-93373480-04c1-11eb-879c-cbf240d2d1af.png)

**Comment by initstring** [comment]
It looks like it cannot connect to your proxy. Are you sure you have a proxy running on 8080? The tool does not include a proxy, you will have to run ZAP or Burp Suite yourself (or something similar).

You should be able to run it with `--proxy 127.0.0.1:8080` or `--proxy "http://127.0.0.1:8080"`

Make sure you can connect to your proxy with curl 127.0.0.1:8080 first.

**Comment by LioMasterRIE** [comment]
Hello,
I can connect to the proxy ..... it is strange .....

![image](https://user-images.githubusercontent.com/38889163/95060241-4db17c00-06fa-11eb-80bb-325479baa53f.png)

linkedin2username is working for google or other big company 
but not working for little one in my case .....
using burp, I can see my browser captured packet, but nothing with your app ....
--proxy 127.0.0.1:8080 is not working
--proxy "http://127.0.0.1:8080" is working !!!! COOL

after some tests, I have to add more connections to the account I am logging in .... 
I tried with another account (with more "connections") and it is working.
