### ISSUE TITLE
302

### ISSUE THREAD

**Issue by lxppx** [initstring/linkedin2username#25]
Always reminds me of this 302 error, do you know how to fix it?

[*] Using version 0.18, which is the latest on GitHub.

[!] Some unknown redirection occurred. If this persists, please open an issue on github.

**Comment by lxppx** [comment]
![bug](https://user-images.githubusercontent.com/42337441/95018249-0d69e380-0691-11eb-8906-2557e61e19d5.png)

**Comment by initstring** [comment]
Thanks for opening an issue!

First, I'd try logging in via the web to make sure it isn't prompting you to check on your account for something. If it's still occurring, is the tool also printing out a DEBUG message that you can share?

**Comment by lxppx** [comment]
I've checked my account and all is well.  It seems that linkedin is causing the problem. I have just had the program run a few times again. At first it was the same error. The fourth time it ran through.

**Comment by initstring** [comment]
Thanks @lxppx . Would you mind sharing the DEBUG info that is printed? It might be helpful in understanding the error in case it is reported again.

**Comment by lxppx** [comment]
I've  reproduced the problem  by creating a new account, I think it‘s because my account was not set up with a main email or a bind email. The program works well  after I bind my email!
This image is the content of "redirect" when no mailbox is set, and it does not conform to the previous judgment statement.
![111](https://user-images.githubusercontent.com/42337441/95039473-696d5000-0703-11eb-966f-2aabc8a1a51f.png)

**Comment by initstring** [comment]
Thank you, this is very helpful!

I've added a message for this 302 to the code and tagged a new version. Enjoy!
