### ISSUE TITLE
Cant login

### ISSUE THREAD

**Issue by Aramics** [initstring/linkedin2username#27]
running this : `python3 linkedin2username.py -u ****@gmail.com -c uber-com -p *****`

always return this : 
`You've been returned to a login page. Check your username and password and try again.`

**Comment by initstring** [comment]
Hi @Aramics - thanks for opening an issue!

I just tested and the tool is still working for me, so at least I know LinkedIn hasn't made a new change that completely breaks the tool.

Are you able to log in ok via the web with the same username and password?

Maybe try the following:

- Are there any weird special characters in your password that maybe the command line is not handling well (like `#` or something)? If so, you can try putting your password in single or double quotes, or not using the `-p` option at all and inputting it when prompted
- You can try using the `--proxy` option to proxy the tool through something like ZAP or Burp so you can clearly see the login request and the response. If you are able to  do that and figure out what is happening, please report back here.

Thanks!

**Comment by Aramics** [comment]
Thanks very much. @initstring 

> Are there any weird special characters in your password that maybe the command line is not handling

This was the problem, i have '&' in my password.

Thanks very much.

**Comment by initstring** [comment]
Great news, thanks for the follow up!
