### ISSUE TITLE
Showing Error -[94m[*] [0mUsing version 0.20, which is the latest on GitHub.  [93m[!] [0mLinkedIn doesn't like something about this login. Maybe you're being sneaky on a VPN or something. You may get an email with a verification token. You can ignore the email. Log in from a web browser and try again.

### ISSUE THREAD

**Issue by Dhavalu585** [initstring/linkedin2username#30]
**Describe the bug**

**To Reproduce**
Please provide the command as you ran it, omitting the target company name if necessary and of course your username and password.

**Verify Expected Results**
Have you verified that you can access the company page via the web UI, and that the expected amount of contacts are visible using your login?

**Additional context**
Do you have any type of special setup? Web proxy, two-factor LI authentication, etc.

**Comment by initstring** [comment]
LinkedIn has flagged something suspicious about the login. Did you try logging in from the same location in your web browser? And that works ok?

**Comment by Dhavalu585** [comment]
Yes it works well from the browser

**Comment by initstring** [comment]
Is there anything different from the console you are running the tool in? Like is it coming from a different source IP address (VPN) or proxy (tor, etc)?

I've just ran the tool myself and verified it still works, so at least LinkedIn hasn't changed something that is globally breaking things yet.

Also, in the future please provide more details in your initial issue. You can see that there was a template of question to answer, but you simply posted the questions with no answers.

**Comment by initstring** [comment]
No reply, closing this.
