### ISSUE TITLE
Missing Spaces

### ISSUE THREAD

**Issue by nimmicus** [initstring/linkedin2username#34]
A space should be added after the ',' preceding 'double-check' ([L382](https://github.com/initstring/linkedin2username/blob/master/linkedin2username.py#L382)): 
[*] Hopefully that's the right company-name! If not,double-check LinkedIn and try again.

A space should be added between 'in' and 'the' ([L720](https://github.com/initstring/linkedin2username/blob/master/linkedin2username.py#L720)):
[*] All done! Check out your lovely new files inthe li2u-output directory.

**Comment by initstring** [comment]
@nimmicus - thanks for pointing this out!

Fixed in https://github.com/initstring/linkedin2username/pull/37.
