### ISSUE TITLE
Off by 1 Running Total

### ISSUE THREAD

**Issue by nimmicus** [initstring/linkedin2username#35]
**Describe the bug**
The running total is one more than the actual results (specifically the rawnames.txt):

[*] Scraping results on loop 2...        [*] Added 7 new names. **Running total: 7**              
[*] We have hit the end of the road! Moving on...

[*] All done! Check out your lovely new files inthe li2u-output directory.
$ wc -l li2u-output/*
       8 li2u-output/we-are-example-f.last.txt
       8 li2u-output/we-are-example-first.last.txt
       6 li2u-output/we-are-example-first.txt
       8 li2u-output/we-are-example-firstl.txt
       8 li2u-output/we-are-example-flast.txt
       8 li2u-output/we-are-example-lastf.txt
       **6 li2u-output/we-are-example-rawnames.txt**
      52 total

**To Reproduce**
$ python3 linkedin2username.py --geoblast -u \<redacted\> -c we-are-example -n example.com.au

**Verify Expected Results**
Have you verified that you can access the company page via the web UI, and that the expected amount of contacts are visible using your login?

Yes.

**Additional context**
Do you have any type of special setup? Web proxy, two-factor LI authentication, etc.

No. Tool version 0.21

**Comment by nimmicus** [comment]
Created a pull request: https://github.com/initstring/linkedin2username/pull/36.

**Comment by initstring** [comment]
Thanks for this! I'll close this issue and we'll get it resolved in the PR.
