### ISSUE TITLE
Does this work with 2FA-enabled account? No issue logging in via browser on same machine.

### ISSUE THREAD

**Issue by desmondkung** [initstring/linkedin2username#39]
[*] Using version 0.21, which is the latest on GitHub.

[!] LinkedIn doesn't like something about this login. Maybe you're being sneaky on a VPN or something. You may get an email with a verification token. You can ignore the email. Log in from a web browser and try again.

**Comment by initstring** [comment]
Sorry, it does not support multi-factor. I just added a note on this in the README, thanks for pointing it out.
