### ISSUE TITLE
doesn't work 

### ISSUE THREAD

**Issue by c4ir0** [initstring/linkedin2username#41]
![Capture](https://user-images.githubusercontent.com/108268587/193701596-a29a1381-ca95-4c56-8a2b-be61328babea.JPG)

**Comment by initstring** [comment]
Hi, thanks for opening this issue. I've actually considered completely removing this version check from the tool. I think it is unnecessary and it just adds overhead to maintain.

Give me a moment and I will fix it right now...

**Comment by initstring** [comment]
Fixed in https://github.com/initstring/linkedin2username/pull/42, thanks again for reporting.
