### ISSUE TITLE
Hey i want to rewrite this code in type script.. is this possible? Thanks mate

### ISSUE THREAD

**Issue by davidnyseen** [initstring/linkedin2username#43]

**Comment by initstring** [comment]
Hello, thanks for opening an issue. :)

I'm not sure if you are asking permission or if you are asking if the typescript language is capable of doing the same things this tool does.

Either way, they answer is yes. :) I'm not a typescript expert myself, so I can't really offer any advice there. But it should be capable - the tool isn't that sophisticated, it basically takes user input, performs HTTP requests, looks for pattern matches, and then transforms strings.

Are you planning to write a browser extension or something?

**Comment by initstring** [comment]
OK, well, good luck! :)
