### ISSUE TITLE
Error Prompting to Login to Web Gui

### ISSUE THREAD

**Issue by C0zturk** [initstring/linkedin2username#57]
**Describe the bug**
Attempting to run a scan against a company, with these arguments:
`python linkedin2username.py -u myemail@email.com -c companyname`
 
The script prompts for my PW which I enter and it accepts however I continue to get the error below
`LinkedIn has a message for you that you need to address.  Please log in using a web browser first, and then come back and try again.`

Have closed the shell, logged in on the web browser > accepted my MFA sign in request and it continues happening.  
Have tried with different company names.  
Have typed pw incorrectly to verify that a different error comes up when intentionally wrong.

**To Reproduce**
Run the script with arguements above.

**Verify Expected Results**
Have you verified that you can access the company page via the web UI, and that the expected amount of contacts are visible using your login? Yes.  Have been manually creating a user list as I can't get my scripts working rofl
![2023-05-18 16_23_55-kali-linux-2022 1-vmware-amd64 - VMware Workstation](https://github.com/initstring/linkedin2username/assets/48399589/68ec67f3-953b-4f21-9168-eba76cfe2335)

**Additional context**
Do you have any type of special setup? No special setup - simply using this script on a kali VM on my windows host machine.

**Comment by initstring** [comment]
Hi @C0zturk -

Thanks for the nice detailed issue. Sorry, but MFA is not supported. [There is a small note in the README about this](https://github.com/initstring/linkedin2username#toubleshooting).
