### ISSUE TITLE
DEBUG INFO: LOCATION: /settings RESPONSE TEXT:

### ISSUE THREAD

**Issue by mikemike01** [initstring/linkedin2username#58]
I was told this when I tried using this script in CMD.

[!] Some unknown redirection occurred. If this persists, please open an issue and include the info below:
DEBUG INFO:
LOCATION: /settings
RESPONSE TEXT:

**Comment by initstring** [comment]
Hi @mikemike01  -

It looks like LinkedIn is redirecting you to a settings page for some reason. I haven't seen this before. If you log in via the web browser, what happens? Does it have some message asking you to do something in settings?

**Comment by initstring** [comment]
No reply, closing.
