### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by okiwoki** [initstring/linkedin2username#8]
I'm getting this when running against a specific client:

[+] Successfully logged in.

Traceback (most recent call last):

File "linkedin2username.py", line 235, in <module>
main()

File "linkedin2username.py", line 228, in main
companyID = get_company_info(company, session)

File "linkedin2username.py", line 99, in get_company_info
foundDesc = re.findall(r'localizedName&quot;:&quot;(.*?)&quot', response.text)[0]

IndexError: list index out of range

**Comment by initstring** [comment]
Hi @okiwoki 

Thank you very much for opening an issue! I can't seem to reproduce this with a few random client names. Would you be able to share the name of the client so I can reproduce? You can contact me directly using my github name at protonmail.

Thanks again!

**Comment by initstring** [comment]
Actually, I think I can guess what the issue is. I added a hack-ish fix to deal with companies who have not added a description.

Can you please pull the new version, try again, and let me know if the issue is fixed? It would be much appreciated.

Good luck with your gig!!!

**Comment by okiwoki** [comment]
That was it! Working flawlessly now. Thanks!

**Comment by initstring** [comment]
Awesome, thanks again for reporting. Enjoy!
